# Copy this file to the Config directory of your application.  Do not put your copy here, put it in your application

development:
  idp_sso_target_url: This is provided by Okta on the General tab under "Embed Link"
  idp_cert_fingerprint: This is created from your certificate.  See the Readme for the command

acceptance:
  idp_sso_target_url: This is provided by Okta on the General tab under "Embed Link"
  idp_cert_fingerprint: This is created from your certificate.  See the Readme for the command